/**
 * Stitch "Vibrant Junior Learn" tasarım sisteminin BİREBİR kopyası.
 * Kaynak: stitch_i_lk_retim_etkile_imli_renme_portal.zip içindeki 4 ekranın
 * <script id="tailwind-config"> bloğu (dördü de aynı). Token adları ve
 * değerleri değiştirilmeden alındı — "birebir uy" talimatı (K14, oturum 002).
 *
 * @type {import('tailwindcss').Config}
 */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "../../packages/manipulatives/src/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#f8f9ff",
        "secondary-fixed": "#acedff",
        "tertiary-fixed": "#6ffbbe",
        "surface-bright": "#f8f9ff",
        "surface-container-low": "#eff4ff",
        "inverse-primary": "#d2bbff",
        surface: "#f8f9ff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed-dim": "#4cd7f6",
        "on-background": "#0b1c30",
        "on-secondary-container": "#006172",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed": "#001f26",
        "surface-container-high": "#dce9ff",
        "on-secondary": "#ffffff",
        tertiary: "#005b3d",
        "surface-dim": "#cbdbf5",
        "surface-variant": "#d3e4fe",
        "secondary-container": "#57dffe",
        outline: "#7b7487",
        "on-primary-fixed": "#25005a",
        "primary-fixed-dim": "#d2bbff",
        "error-container": "#ffdad6",
        "tertiary-container": "#007650",
        "on-primary-container": "#ede0ff",
        "surface-container": "#e5eeff",
        primary: "#630ed4",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#4a4455",
        "outline-variant": "#ccc3d8",
        "on-error-container": "#93000a",
        "primary-container": "#7c3aed",
        "on-secondary-fixed-variant": "#004e5c",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-fixed-dim": "#4edea3",
        secondary: "#00687a",
        "surface-tint": "#732ee4",
        "on-error": "#ffffff",
        "on-surface": "#0b1c30",
        "on-tertiary-container": "#76ffc2",
        "primary-fixed": "#eaddff",
        error: "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#5a00c6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "2rem",
        gutter: "1.25rem",
        margin: "1.5rem",
        "space-md": "1.25rem",
        "space-xl": "3rem",
        "space-xs": "0.375rem",
        "space-sm": "0.75rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-lg": ["16px", { lineHeight: "22px", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "18px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg-mobile": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "display-lg": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
